import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>

      <main className={"text-center mt-10"}>
        <h1 className={"text-5xl p-2"}>Welcome to Walters Blog on Coffee!</h1>

        <h2 className={"text-3xl p-4"}>This is a sample blog built with Next.js.</h2>
      </main>
    </div>
  );
};

export default Home;
